using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace TestsGenerator;

public class CodeRewriter : CSharpSyntaxRewriter
{
    public CodeWalker CodeWalker = new();

    public CodeRewriter() : base(true)
    {
    }

    public override SyntaxNode? VisitFileScopedNamespaceDeclaration(FileScopedNamespaceDeclarationSyntax node)
    {
        node.Name.GetText();
        node = node.WithName(node.Name);
        return node;
    }

    public SyntaxTree GenerateTestClass(SyntaxNode root)
    {
        CodeWalker.Visit(root);
        var classList = new MemberDeclarationSyntax[CodeWalker.Classes.Count];
        int i = 0;
        foreach (var classDeclarationSyntax in CodeWalker.Classes)
        {
            var methodList = new MemberDeclarationSyntax[classDeclarationSyntax.ChildNodes().Count()];
            int j = 0;
            foreach (var childNode in classDeclarationSyntax.ChildNodes())
            {
                var node = (MethodDeclarationSyntax)childNode;
                methodList[j++]=(MethodDeclaration
                    (PredefinedType
                        (Token
                            (SyntaxKind.VoidKeyword)),
                        Identifier(node.Identifier + "Test"))
                    .WithAttributeLists(
                        SingletonList<AttributeListSyntax>(
                            AttributeList(
                                SingletonSeparatedList<AttributeSyntax>(
                                    Attribute(
                                        IdentifierName("Test"))))))
                    .WithModifiers(
                        TokenList(
                            Token(SyntaxKind.PublicKeyword))).WithBody(
                        Block(
                            SingletonList<StatementSyntax>(
                                ExpressionStatement(
                                    InvocationExpression(
                                            MemberAccessExpression(
                                                SyntaxKind.SimpleMemberAccessExpression,
                                                IdentifierName("Assert"),
                                                IdentifierName("Fail")))
                                        .WithArgumentList(
                                            ArgumentList(
                                                SingletonSeparatedList<ArgumentSyntax>(
                                                    Argument(
                                                        LiteralExpression(
                                                            SyntaxKind.StringLiteralExpression,
                                                            Literal("autogenerated")))))))))));
            }
            classList[i++] = (ClassDeclaration(classDeclarationSyntax.Identifier + "Tests")
                .WithAttributeLists(
                SingletonList<AttributeListSyntax>(
                        AttributeList(
                            SingletonSeparatedList<AttributeSyntax>(
                                Attribute(
                                    IdentifierName("TestFixture"))))))
                .WithModifiers(TokenList
                (Token
                    (SyntaxKind.PublicKeyword)))
                .WithMembers(new SyntaxList<MemberDeclarationSyntax>(methodList)));
        }
        
        return SyntaxTree(CompilationUnit()
    .WithMembers(
        SingletonList<MemberDeclarationSyntax>(
            FileScopedNamespaceDeclaration(
                    IdentifierName(CodeWalker.fileNamespace))
                .WithMembers(new SyntaxList<MemberDeclarationSyntax>(classList)
                    )))
    .NormalizeWhitespace());
    }
}